language: ruby
rvm:
  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - jruby
  - rbx-2
gemfile:
  - .gemfiles/rails3_2.gemfile
  - .gemfiles/rails4_0.gemfile
  - .gemfiles/rails4_1.gemfile
  - .gemfiles/rails4_2.gemfile
